### PR TITLE
Update API endpoints

### PR DESCRIPTION
**Pull request by marc0der**
- Update platforms in README.
- Update API endpoints.

### CODE REVIEW

**Comment by helpermethod** [comment]
LGTM!

**Review by helpermethod — APPROVED** [review]
LGTM!

**Comment by marc0der** [comment]
@big-guy I'm not sure what was required to release this. If I remember correctly, you released the 3.0.0 version yourself. Can you remember?

**Comment by marc0der** [comment]
@big-guy I forgot about this and just merged it. Can you remind me about the release process, please?

**Pull request merged**
